---
deployment:
  tasks:
    restart: |
      source /home/jihapikkshan/nodevenv/touristic/20/bin/activate && cd /home/jihapikkshan/touristic
      npm install --production
      npm stop
      npm start
